import os
import argparse
import numpy as np


def make_split(root: str, split: str, num_files: int, T: int, D: int, seed: int = 123):
    rng = np.random.default_rng(seed)
    out_dir = os.path.join(root, split)
    os.makedirs(out_dir, exist_ok=True)

    for i in range(num_files):
        # latent trajectory: 2D smooth curve with random control points
        t = np.linspace(0, 1, T)
        cx, cy = rng.uniform(-10, 10, size=3), rng.uniform(-10, 10, size=3)
        px = np.poly1d(rng.normal(size=3))
        py = np.poly1d(rng.normal(size=3))
        pos = np.stack([
            np.interp(t, [0, 0.5, 1], cx) + 0.5 * np.sin(2*np.pi*t) + px(t)*0.1,
            np.interp(t, [0, 0.5, 1], cy) + 0.5 * np.cos(2*np.pi*t) + py(t)*0.1,
        ], axis=-1).astype(np.float32)

        # CSI is generated by linear projection of latent + AR noise
        W = rng.normal(size=(2, D)).astype(np.float32) * 0.5
        csi = pos @ W + rng.normal(scale=0.2, size=(T, D)).astype(np.float32)
        # add temporal correlation
        for d in range(D):
            for t_idx in range(1, T):
                csi[t_idx, d] = 0.9 * csi[t_idx-1, d] + 0.1 * csi[t_idx, d]

        # weak labels: noisy + downsampled then upsampled
        down = pos[::4]
        noise = rng.normal(scale=1.0, size=down.shape).astype(np.float32)
        down_noisy = down + noise
        pos_weak = np.repeat(down_noisy, 4, axis=0)[:T]

        np.savez(os.path.join(out_dir, f"sample_{i:04d}.npz"), csi=csi, pos=pos, pos_weak=pos_weak)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=str, default="data/synth")
    ap.add_argument("--train_files", type=int, default=16)
    ap.add_argument("--val_files", type=int, default=4)
    ap.add_argument("--test_files", type=int, default=4)
    ap.add_argument("--T", type=int, default=256)
    ap.add_argument("--D", type=int, default=64)
    args = ap.parse_args()

    make_split(args.root, "train", args.train_files, args.T, args.D, seed=123)
    make_split(args.root, "val", args.val_files, args.T, args.D, seed=456)
    make_split(args.root, "test", args.test_files, args.T, args.D, seed=789)
    print("Synthetic dataset created at", args.root)


if __name__ == "__main__":
    main()
